version: "2"

services:
  nginx:
    build: ./nginx
    image: evgeniy-khyst/nginx
    env_file:
      - ./config.env
    volumes:
      - nginx_conf:/etc/nginx/sites
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
      - ./vhosts:/etc/nginx/vhosts
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    build: ./certbot
    image: evgeniy-khyst/certbot
    env_file:
      - ./config.env
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot

  cron:
    build: ./cron
    image: evgeniy-khyst/cron
    environment:
      - COMPOSE_PROJECT_NAME=balkon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    restart: unless-stopped

  lovemanifest:
    image: vahpetr/lovemanifest:1.0.2211280030
    environment:
      - NGINX_PORT=5000
    ports:
      - 5000:5000
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5000/internal/health"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2022-11-11T03-44-20Z
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKET=balkon
      # - MINIO_SITE_REGION=${S3_REGION}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  imgcdn:
    image: darthsim/imgproxy:v3.10.0
    environment:
      - IMGPROXY_KEY=${IMGPROXY_KEY}
      - IMGPROXY_SALT=${IMGPROXY_SALT}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - IMGPROXY_USE_S3=true
      - IMGPROXY_S3_ENDPOINT=http://minio:9000
      - IMGPROXY_SERVER_NAME=imgcdn.balkon.dev
      - IMGPROXY_USE_ETAG=true
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_ENABLE_CLIENT_HINTS=true
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_ALLOW_ORIGIN=*
      - IMGPROXY_TTL=60
      - IMGPROXY_ENABLE_DEBUG_HEADERS=false
      - IMGPROXY_WATERMARK_URL=http://minio:9000/lovemanifest/media/watermark.svg
      - IMGPROXY_BASE_URL=http://minio:9000
      # - IMGPROXY_S3_REGION=${S3_REGION}
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  nginx_conf:
    external: true
  letsencrypt_certs:
    external: true
  certbot_acme_challenge:
  minio_data:
    external: true
